export const greatCompliments = [
	'Nice!',
	'Great!',
	'Awesome!',
	'Sweet!',
	'Perfect!',
	'Excellent!',
	'Brilliant!',
	'Well done!',
	'Clean hit!',
	'Super clean!',
	'Nailed it!',
	'You got it!',
	'Lovely!',
	'Solid!',
	'Sharp work!',
	'Wonderful!',
	'Beautiful!',
	'Yes!',
	'Boom!',
	'Crushed it!',
	'Flawless!',
	'Golden!',
	'Top notch!',
	'Nice touch!',
	'So good!',
	'Strong hit!',
	'Great ear!',
	'Superb!',
	'Legendary!',
	'Keep it up!',
	'Smooth!',
	'Crisp!',
	'Minty!',
	'Classy!',
	'Clean tone!',
	'Huge win!',
	'Right there!',
	'Brava!',
	'Bravo!',
	'Pure gold!',
	'Big yes!',
	'Great job!',
	'Excellent hit!',
	'Strong note!',
	'Sweet note!',
	'Fine playing!',
	'Gorgeous!',
	'Power move!',
	'Super move!',
	'Great sound!',
	'Stellar!',
	'Outstanding!',
	'Phenomenal!',
	'Impressive!',
	'Fantastic!',
	'Incredible!',
	'Remarkable!',
	'Skilled!',
	'Smart play!',
	'Quick ear!',
	'Good catch!',
	'Excellent ear!',
	'Great timing!',
	'Way to go!',
	'That’s it!',
	'That works!',
	'Yes indeed!',
	'Keep rolling!',
	'Keep shining!',
	'Keep cooking!',
	'Hot streak!',
	'On fire!',
	'You rock!',
	'You shine!',
	'So smooth!',
	'So clean!',
	'Steady hand!',
	'Solid tone!',
	'Sweet tone!',
	'Rich tone!',
	'Great form!',
	'Great effort!',
	'Great energy!',
	'Music to my ears!',
	'What a hit!',
	'What a note!',
	'What a sound!',
	'Clean strike!',
	'Tidy!',
	'Slick!',
	'Snappy!',
	'Polished!',
	'Refined!',
	'Ear power!',
	'Ultra clean!',
	'A+!',
	'Gold star!',
	'Star move!',
	'Winning note!',
	'Winning hit!',
	'You nailed that!',
	'You’re flying!',
	'You’re unstoppable!',
	'Step by step!',
	'Nice progress!',
	'Great progress!',
	'Smart musician!',
	'Great musician!',
	'Fine musician!',
	'Confident hit!',
	'Confident note!',
	'Brave sound!',
	'Proud of that!',
	'Sweet success!',
	'Big success!',
	'Major win!',
	'Wonderful hit!',
	'Spectacular!',
	'Jaw-dropping!',
	'Peak playing!',
	'Masterful!',
	'Champion move!',
	'Winner!',
	'Great consistency!',
	'Steady progress!',
	'You got this!',
	'So impressive!',
	'Best yet!',
	'Next level!',
	'Mega clean!',
	'Fantastic ear!',
	'Great resonance!',
	'Lovely resonance!',
	'Bright sound!',
	'Balanced sound!',
	'Nice one!',
	'Great one!',
	'That was clean!',
	'That was perfect!',
	'That was beautiful!',
	'Absolutely beautiful!',
	'Terrific!',
	'Superstar!',
	'All star!',
	'Rock solid!',
	'So elegant!',
	'Fresh!',
	'Prime!',
	'Strong finish!',
	'Great start!',
	'Great middle!',
	'Great recovery!',
	'Nice rebound!',
	'Stay strong!',
	'Keep going!',
	'Right idea!',
	'Big brain move!',
	'Nice listening!',
	'Fine listening!',
	'Super listening!',
	'So musical!',
	'Lovely phrasing!',
	'Great musicality!',
	'Couldn’t miss!',
	'Great instincts!',
	'Amazing instincts!',
	'Elite!',
	'Fire!',
	'Pure class!',
	'100%!',
	'10/10!',
	'Perfectly done!'
] as const;

export const preciseHitCompliments = [
	'Spot on!',
	'On point!',
	'Right on!',
	'Pitch perfect!',
	'So precise!',
	'Locked in!',
	'In tune!',
	'Exactly!',
	'Perfect hit!',
	'Beautiful pitch!',
	'Perfect pitch!',
	'So tight!',
	'Super tight!',
	'Great control!',
	'Great focus!',
	'Steady ear!',
	'Nice control!',
	'Couldn’t be better!',
	'Spotless!',
	'Right in!',
	'Bulls-eye!',
	'Center hit!',
	'Sharp ear!',
	'Fine ear!',
	'Spotless pitch!',
	'Pitch locked!',
	'Perfect center!',
	'Absolutely right!',
	'You’re locked in!',
	'Totally right!',
	'Picture perfect!',
	'Super accurate!',
	'Pinpoint!',
	'Laser focus!',
	'Excellent control!',
	'Ultra precise!',
	'Great precision!',
	'Perfect precision!',
	'Excellent precision!',
	'Great intonation!',
	'Excellent intonation!',
	'Beautiful intonation!',
	'Yes, exactly!',
	'That’s the note!',
	'Nailed the pitch!',
	'Pitch on lock!',
	'What precision!',
	'What control!',
	'Ice cold precision!'
] as const;

export const getRandomCompliment = (mode: 'great' | 'precise'): string => {
	const compliments = mode === 'great' ? greatCompliments : preciseHitCompliments;
	return compliments[Math.floor(Math.random() * compliments.length)];
};
